name: .NET Framework Desktop

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name'
        required: true
        default: 'Release'
      tag:
        description: 'Tag'
        required: true
        default: 'v'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        targetplatform: [x86, x64]

    runs-on: windows-latest  
    
    env:
      Solution_Name: GameCaptureForDiscord.sln
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Packages
      run: nuget restore $env:Solution_Name
      
    - name: Create Release Directory
      run: mkdir _release
      
    - name: Compile the application
      run: msbuild $env:Solution_Name /p:platform=$env:TargetPlatform /p:configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        TargetPlatform: ${{ matrix.targetplatform }}

    # Archive the package
    - name: Create archive
      run: Compress-Archive -Path ${{ github.workspace }}\bin\$env:TargetPlatform\$env:Configuration\* -DestinationPath ${{ github.workspace }}\_release\GCFD_$env:TargetPlatform_$env:Configuration.zip
      env:
        Configuration: ${{ matrix.configuration }}
        TargetPlatform: ${{ matrix.targetplatform }}
    
    # Create the release: https://github.com/ncipollo/release-action
    - name: Create release
      id: create_release
      uses: ncipollo/release-action
      env:
        Configuration: ${{ matrix.configuration }}
        TargetPlatform: ${{ matrix.targetplatform }}
      with:
        allowUpdates: true
        tag: refs/tags/${{ github.event.inputs.tag }}
        name: ${{ github.event.inputs.name }} ${{ github.event.inputs.tag }}
        replacesArtifacts: false
        token: ${{ secrets.GITHUB_TOKEN }}
        
    # Upload release asset:   https://github.com/actions/upload-release-asset
    - name: Update release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        Configuration: ${{ matrix.configuration }}
        TargetPlatform: ${{ matrix.targetplatform }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ${{ github.workspace }}\_release\GCFD_$env:TargetPlatform_$env:Configuration.zip
        asset_name: GCFD_$env:TargetPlatform_$env:Configuration.zip
        asset_content_type: application/zip
